<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>Roslynator.ConfigurationFileGenerator</AssemblyName>
    <RootNamespace>Roslynator.ConfigurationFileGenerator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(RoslynatorRoslynVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeGeneration\CodeGeneration.csproj" />
  </ItemGroup>

</Project>
